(function(){
  'use strict';
  var KEY='bbv_cart_v1';
  var cart=[];
  try{cart=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(cart))cart=[];}catch(_){cart=[];}
  function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function money(v){return Number(v||0).toLocaleString('vi-VN')+'₫';}
  function price(v){var n=String(v||'').replace(/[^0-9]/g,'');return n?Number(n):0;}
  function save(){localStorage.setItem(KEY,JSON.stringify(cart));render();}
  function totalQty(){return cart.reduce(function(s,i){return s+i.quantity;},0);}
  function total(){return cart.reduce(function(s,i){return s+i.price*i.quantity;},0);}
  var root=document.createElement('div');
  root.innerHTML='<button class="bbv-cart-trigger" type="button" aria-label="Mở giỏ hàng"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><path d="M3 6h18M16 10a4 4 0 01-8 0"/></svg><span class="bbv-cart-count">0</span></button><div class="bbv-commerce-overlay" aria-hidden="true"><aside class="bbv-commerce-panel" role="dialog" aria-modal="true" aria-label="Giỏ hàng"><div class="bbv-cart-view"><div class="bbv-cart-head"><h2>Giỏ hàng</h2><button class="bbv-close" aria-label="Đóng">×</button></div><div class="bbv-cart-body"></div><div class="bbv-cart-foot"><div class="bbv-total"><span>Tạm tính</span><strong>0₫</strong></div><button class="bbv-primary bbv-to-checkout">Đặt hàng giao tận nơi</button></div></div><form class="bbv-checkout"><button class="bbv-back" type="button">← Quay lại giỏ hàng</button><h3>Thông tin nhận hàng</h3><p class="bbv-checkout-intro">Thanh toán khi nhận hàng. Shop sẽ gọi xác nhận phí vận chuyển trước khi gửi.</p><div class="bbv-field"><label for="bbv-name">Họ và tên *</label><input id="bbv-name" name="customer_name" autocomplete="name" required></div><div class="bbv-field"><label for="bbv-phone">Số điện thoại *</label><input id="bbv-phone" name="customer_phone" inputmode="tel" autocomplete="tel" required></div><div class="bbv-field"><label for="bbv-address">Địa chỉ *</label><input id="bbv-address" name="customer_address" autocomplete="street-address" required></div><div class="bbv-row"><div class="bbv-field"><label for="bbv-province">Tỉnh / Thành phố *</label><input id="bbv-province" name="customer_province" required></div><div class="bbv-field"><label for="bbv-district">Quận / Huyện</label><input id="bbv-district" name="customer_district"></div></div><div class="bbv-field"><label for="bbv-ward">Phường / Xã</label><input id="bbv-ward" name="customer_ward"></div><div class="bbv-field"><label for="bbv-note">Ghi chú</label><textarea id="bbv-note" name="notes" rows="3"></textarea></div><div class="bbv-checkout-error" role="alert"></div><button class="bbv-primary" type="submit">Xác nhận đặt hàng</button></form></aside></div>';
  while(root.firstChild)document.body.appendChild(root.firstChild);
  var trigger=document.querySelector('.bbv-cart-trigger'),overlay=document.querySelector('.bbv-commerce-overlay'),panel=document.querySelector('.bbv-commerce-panel'),body=document.querySelector('.bbv-cart-body'),form=document.querySelector('.bbv-checkout');
  function open(){overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.querySelector('.bbv-close').focus();}
  function close(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');panel.classList.remove('checkout');document.body.style.overflow='';trigger.focus();}
  function render(){document.querySelector('.bbv-cart-count').textContent=totalQty();document.querySelector('.bbv-total strong').textContent=money(total());body.innerHTML=cart.length?cart.map(function(i,n){return '<div class="bbv-cart-item"><img src="'+esc(i.image||'/logo_bongbanviet.png')+'" alt=""><div><div class="bbv-item-name">'+esc(i.name)+'</div>'+(i.variant?'<div class="bbv-item-var">'+esc(i.variant)+'</div>':'')+'<div class="bbv-item-price">'+money(i.price)+'</div><button class="bbv-remove" data-remove="'+n+'">Xóa</button></div><div class="bbv-qty"><button type="button" data-delta="-1" data-index="'+n+'">−</button><span>'+i.quantity+'</span><button type="button" data-delta="1" data-index="'+n+'">+</button></div></div>';}).join(''):'<div class="bbv-cart-empty"><strong>Giỏ hàng đang trống</strong><br>Chọn sản phẩm để bắt đầu đơn hàng.</div>';}
  trigger.addEventListener('click',open);document.querySelector('.bbv-close').addEventListener('click',close);overlay.addEventListener('click',function(e){if(e.target===overlay)close();});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&overlay.classList.contains('open'))close();});
  body.addEventListener('click',function(e){var r=e.target.getAttribute('data-remove'),d=e.target.getAttribute('data-delta'),n=Number(e.target.getAttribute('data-index'));if(r!==null){cart.splice(Number(r),1);save();}else if(d){cart[n].quantity=Math.max(1,Math.min(20,cart[n].quantity+Number(d)));save();}});
  document.querySelector('.bbv-to-checkout').addEventListener('click',function(){if(!cart.length)return;panel.classList.add('checkout');form.querySelector('input').focus();});document.querySelector('.bbv-back').addEventListener('click',function(){panel.classList.remove('checkout');});
  function installAddButton(){var actions=document.querySelector('.pd-actions');if(!actions||document.getElementById('pdAddCart'))return;var b=document.createElement('button');b.id='pdAddCart';b.type='button';b.className='bbv-add-cart';b.textContent='Thêm vào giỏ';actions.insertBefore(b,actions.firstChild);b.addEventListener('click',function(){var p=window.BBV_ACTIVE_PRODUCT;if(!p)return;var variant=window.BBV_ACTIVE_VARIANT||'';var variants=Array.isArray(p.variants)?p.variants:[];var selected=variants.find(function(v){return String(v.name||'')===variant;});var unit=price(selected&&selected.price||p.price);if(!unit){alert('Sản phẩm này chưa có giá trực tuyến. Vui lòng liên hệ shop.');return;}var id=p.slug+'::'+variant;var found=cart.find(function(i){return i.id===id;});if(found)found.quantity=Math.min(20,found.quantity+1);else cart.push({id:id,slug:p.slug,name:p.name,variant:variant,image:(selected&&selected.image)||(p.images&&p.images[0])||'',price:unit,quantity:1});save();open();});}
  installAddButton();
  form.addEventListener('submit',async function(e){e.preventDefault();var error=form.querySelector('.bbv-checkout-error'),button=form.querySelector('[type=submit]');error.classList.remove('show');button.disabled=true;button.textContent='Đang tạo đơn...';var data=Object.fromEntries(new FormData(form).entries());data.items=cart.map(function(i){return{slug:i.slug,variant:i.variant,quantity:i.quantity};});data.request_id=sessionStorage.getItem('bbv_checkout_id')||((Date.now().toString(36)+Math.random().toString(36).slice(2)));sessionStorage.setItem('bbv_checkout_id',data.request_id);try{var response=await fetch('/api/storefront/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});var result=await response.json();if(!response.ok)throw new Error(result.error||'Không thể tạo đơn hàng.');cart=[];save();sessionStorage.removeItem('bbv_checkout_id');panel.innerHTML='<div class="bbv-success"><div style="font-size:45px">✓</div><strong>Đặt hàng thành công</strong><p>Mã đơn: <b>'+esc(result.id)+'</b><br>Tổng tiền hàng: '+money(result.total_amount)+'<br>Shop sẽ gọi xác nhận trước khi giao.</p><button class="bbv-primary" type="button" onclick="location.reload()">Tiếp tục mua sắm</button></div>';}catch(err){error.textContent=err.message;error.classList.add('show');button.disabled=false;button.textContent='Xác nhận đặt hàng';}});
  var originalTitle=document.title;
  var originalCanonical=(document.querySelector('link[rel="canonical"]')||{}).href||location.origin+'/';
  function setMeta(selector,attr,value){var el=document.querySelector(selector);if(!el){el=document.createElement('meta');if(selector.indexOf('property=')>-1)el.setAttribute('property',selector.match(/"([^"]+)"/)[1]);else el.setAttribute('name',selector.match(/"([^"]+)"/)[1]);document.head.appendChild(el);}el.setAttribute(attr,value);}
  window.addEventListener('bbv:product-open',function(event){var p=event.detail||{};var title=(p.name||'Sản phẩm')+' | BÓNG BÀN VIỆT';var clean=(p.category_slug&&p.brand_slug&&p.brand_slug!=='khac')?'/'+[p.category_slug,p.brand_slug,p.slug].map(encodeURIComponent).join('/'):'/san-pham.html?id='+encodeURIComponent(p.slug||'');var description=String(p.description||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,158);var image=(p.images&&p.images[0])||'/logo_bongbanviet.png';document.title=title;history.replaceState(history.state,'',clean);var canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical);}canonical.href=location.origin+clean;setMeta('meta[property="og:title"]','content',title);setMeta('meta[property="og:description"]','content',description);setMeta('meta[property="og:image"]','content',new URL(image,location.origin).href);var old=document.getElementById('bbv-product-jsonld');if(old)old.remove();var json=document.createElement('script');json.id='bbv-product-jsonld';json.type='application/ld+json';json.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:p.name,image:p.images||[],description:description,sku:p.id||p.slug,brand:p.brand_slug?{'@type':'Brand',name:p.brand_slug}:undefined,offers:price(p.price)?{'@type':'Offer',priceCurrency:'VND',price:price(p.price),availability:p.in_stock===false?'https://schema.org/OutOfStock':'https://schema.org/InStock',url:location.href}:undefined});document.head.appendChild(json);});
  window.addEventListener('bbv:product-close',function(){document.title=originalTitle;var canonical=document.querySelector('link[rel="canonical"]');if(canonical)canonical.href=originalCanonical;var json=document.getElementById('bbv-product-jsonld');if(json)json.remove();if(location.pathname!=='/'&&history.state&&history.state.modal==='prodDrawer')history.replaceState(null,'','/');});
  document.addEventListener('keydown',function(e){var active=document.querySelector('.bbv-commerce-overlay.open .bbv-commerce-panel, #prodDrawer.open');if(!active||e.key!=='Tab')return;var focusable=Array.from(active.querySelectorAll('button,[href],input,textarea,select,[tabindex]:not([tabindex="-1"])')).filter(function(el){return!el.disabled&&el.offsetParent!==null;});if(!focusable.length)return;var first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
  async function openDirectProduct(attempt){var parts=location.pathname.split('/').filter(Boolean);if(parts.length<3)return;var slug=decodeURIComponent(parts[parts.length-1].replace(/\.html$/i,''));if(typeof window.BBV_SHOW_PRODUCT==='function'){try{var response=await fetch('/api/products/'+encodeURIComponent(slug));if(response.ok)window.BBV_SHOW_PRODUCT(await response.json());return;}catch(_){}}var card=Array.from(document.querySelectorAll('.prod-card')).find(function(el){return decodeURIComponent(String(el.getAttribute('href')||'')).replace(/\.html$/i,'').endsWith('/'+slug)||String(el.getAttribute('href')||'').indexOf('id='+encodeURIComponent(slug))>-1;});if(card){card.click();return;}if((attempt||0)<8)setTimeout(function(){openDirectProduct((attempt||0)+1);},250);}
  render();
  openDirectProduct();
})();
